base: '/advent-of-typo3/'
languages:
  -
    title: English
    enabled: true
    locale: en-US
    hreflang: ''
    base: /
    websiteTitle: ''
    navigationTitle: English
    flag: us
    languageId: 0
rootPageId: 3
websiteTitle: ''
dependencies:
  - surfcamp/success-advent
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=9'
