ui:
  theme: "system"
  name: "Surfboard Company"
  font:
    text: "roboto"
    heading: "roboto-slab"
  layout:
    navigation:
      position: "below"
      isVisible: true
    radius: "5px"
    rotate: "3deg"
    font:
      text: "Roboto, sans-serif"
      heading: "Roboto Slab, serif"
  light:
    color:
      primary: "rgb(235, 183, 35)"
      secondary: "rgb(94, 13, 25)"
      light: "rgb(255, 249, 232)"
      primarytext: "black"
      secondarytext: "white"
      lighttext: "black"
  dark:
    font: []
    color:
      primary: "rgb(235, 183, 35)"
      secondary: "rgb(94, 13, 25)"
      light: "rgb(255, 249, 232)"

