ui:
  theme: "system"
  default:
    font:
      text: "Roboto, sans-serif"
      heading: "Roboto, sans-serif"
    color:
      primary: "rgb(235, 183, 35)"
      secondary: "rgb(94, 13, 25)"
      light: "rgb(255, 249, 232)"
      primarytext: "black"
      secondarytext: "white"
      lighttext: "black"
    setting:
      radius: "5px"
      rotate: "3deg"
  dark:
    font: []
    color:
      primary: "rgb(235, 183, 35)"
      secondary: "rgb(94, 13, 25)"
      light: "rgb(255, 249, 232)"
#  footer:
#    maxCols: 4
#    storagePid: 123456


# DUMMYDATA
#todo replace this values by backend ui input
  info:
    owner:
      name: "Surfcompany Ltd."
      street: "Carretera Matorral 1"
      city: "35610 Puerto del Rosario, España"
      phone: "+34 32 16 8"
      mail: "surfcompany@beachwaves.com"
      imprint: "https://mainpage.com/imprint"
      dataPrivacy: "https://mainpage.com/dataprivacy"
