ui:
  theme: "system"
  layout:
    navigation:
      position: "below"
      isVisible: true
    radius: "5px"
    rotate: "3deg"
    font:
      text: "Roboto, sans-serif"
      heading: "Roboto, sans-serif"
  light:
    color:
      primary: "rgb(235, 183, 35)"
      secondary: "rgb(94, 13, 25)"
      light: "rgb(255, 249, 232)"
      primarytext: "black"
      secondarytext: "white"
      lighttext: "black"
  dark:
    font: []
    color:
      primary: "rgb(235, 183, 35)"
      secondary: "rgb(94, 13, 25)"
      light: "rgb(255, 249, 232)"

# DUMMYDATA
#todo replace this values by backend ui input
info:
  owner:
    name: "Surfcompany Ltd."
    imprint: "https://mainpage.com/imprint"
    dataPrivacy: "https://mainpage.com/dataprivacy"
footer:
  maxCols: '3'
  pageId: 7
