ui:
  theme: "system"
  default:
    font:
      text: "Roboto, sans-serif"
      heading: "Roboto, sans-serif"
    color:
      primary: "rgb(235, 183, 35)"
      secondary: "rgb(94, 13, 25)"
      light: "rgb(255, 249, 232)"
      primarytext: "black"
      secondarytext: "white"
      lighttext: "black"
    setting:
      radius: "5px"
      rotate: "3deg"
      name: 'Surfboard Company'
  dark:
    font: []
    color:
      primary: "rgb(235, 183, 35)"
      secondary: "rgb(94, 13, 25)"
      light: "rgb(255, 249, 232)"
