ui:
  theme: "system"
  layout:
    radius: "5px"
    rotate: "3deg"
    pagebg: "light"
    footerbg: "light"
    backToTopButton: true
    font:
      text: "roboto"
      heading: "roboto-slab"
  light:
    color:
      primary: "rgb(235, 183, 35)"
      secondary: "rgb(94, 13, 25)"
      light: "rgb(255, 249, 232)"
      primarytext: "black"
      secondarytext: "white"
      lighttext: "black"
  dark:
    color:
      primary: "rgb(205, 156, 19)"
      secondary: "rgb(37, 37, 37)"
      light: "rgb(29, 29, 29)"
      primarytext: "black"
      secondarytext: "white"
      lighttext: "white"
info:
  owner:
    name: "Surfcompany Ltd."
    imprint: "https://mainpage.com/imprint"
    dataPrivacy: "https://mainpage.com/dataprivacy"
footer:
  maxCols: '3'
  pageId: 7
