settings:
#  ui.info:
#    label: "Site owners information"
#    owner:
#      name:
#        label: "Name/Company Name"
#        type: string
#        value: "Surfcompany GmbH"
#      street:
#        label: "Street + Housenumber"
#        type: string
#      city:
#        label: "ZIP, City"
#        type: string
#      phone:
#        label: "Phonenumber"
#        type: string
#      mail:
#        label: "Mail address"
#        type: string
#      imprint:
#        label: "Imprint Information"
#        type: string(URL) | TYPO3 PageId (Select-Helper)
#      dataPrivacy:
#        label: "Data Privacy Information"
#        type: string(URL) | TYPO3 PageId (Select-Helper)
#    logo:
  ui.theme:
    label: 'Theme'
    description: 'Values: "system" | "light" | "dark" | "light:only" | "dark:only"'
    type: string
    default: system
  ui.default.font.text:
    label: 'Default theme: Text font'
    type: string #could be stringlist ?!
    default: 'sans-serif'
  ui.default.font.heading:
    label: 'Default theme: Headline font'
    type: string #could be stringlist ?!
    default: 'sans-serif'
  ui.default.color.primary:
    label: 'Default theme: Headline font'
    type: color
    default: 'rgb(1 97 239)'
  ui.footer:
    maxCols:
      label: 'Max Footer columns'
      description: 'Values:Label | 4:auto  | 3:3 | 2:2 | 1:1'
      type: stringList
      default: 'auto'


# todo: implement definitions
#    colors:
#      default: rgb(16 16 16)
#      heading: rgb(0 0 0)
#      muted: rgb(16 16 16 / 66%)
#      bgPage: rgb(255 255 255)
#      primary: rgb(1 97 239)
#      secondary: rgb(1 84 207)
#      accent: rgb(109 40 217)
#    dark:
#      fonts: { }
#      colors:
#        default: rgb(229 236 246)
#        heading: rgb(247, 248, 248)
#        muted: rgb(229 236 246 / 66%)
#        bgPage: rgb(3 6 32)
#        primary: rgb(1 97 239)
#        secondary: rgb(1 84 207)
#        accent: rgb(109 40 217)
