settings:
  info.owner.name:
    label: "Name/Company Name"
    type: string
    default: "Successfull Company Name"
  info.owner.imprint:
    label: "Imprint Information (Page ID or URL)"
    description: 'Page Id or URL to Imprint Information'
    type: string #string(URL) | TYPO3 PageId (Select-Helper)
    default: "https://success.typo3.org/imprint"
  info.owner.dataPrivacy:
    label: "Data Privacy Information"
    description: 'Page Id or URL to Privacy Information'
    type: string #string(URL) | TYPO3 PageId (Select-Helper)
    default: "https://success.typo3.org/imprint"
  ui.theme:
    label: 'Theme'
    description: 'Values: "system" | "light" | "dark" | "light:only" | "dark:only"'
    type: string #would be great to have a select input
    default: system
  ui.layout.radius:
    label: 'Radius'
    description: 'Value should include px, rem, ... f.g "3px" or "0.5rem".'
    type: string
    default: '0'
  ui.layout.rotate:
    label: 'Rotation'
    description: 'Defines if some elements should be rotated. Value should include "deg" e.g. "3deg" or "-4deg".'
    type: string
    default: '0'
  ui.layout.pagebg:
    label: 'Background of page'
    description: 'Values: "primary" | "secondary" | "light" | "white"'
    type: string #would be great to have a select input
    default: 'light'
  ui.layout.footerbg:
    label: 'Background of footer'
    description: 'Values: "primary" | "secondary" | "light" | "white"'
    type: string #would be great to have a select input
    default: 'light'
  ui.backToTopButton:
    label: 'Back to Top Button'
    type: bool
    default: false
  ui.font.text:
    label: 'Text font'
    description: 'Values: "Comic Neue" | "Lato" | "Merriweather" | "Noto Serif" | "Open Sans" | "Oswald" | "Playpen Sans" | "Roboto Slab" | "Roboto Mono" | "Roboto"'
    type: string #would be great to have a select input
    default: 'Open Sans'
  ui.font.heading:
    label: 'Headline font'
    description: 'Values: "Comic Neue" | "Lato" | "Merriweather" | "Noto Serif" | "Open Sans" | "Oswald" | "Playpen Sans" | "Roboto Slab" | "Roboto Mono" | "Roboto"'
    type: string  #would be great to have a select input
    default: 'Open Sans'
  footer.maxCols:
    label: 'Max Footer columns'
    description: 'Values: "auto" | "4" | "3" | "2" | "1"'
    type: string
    default: 'auto'
  footer.pageId:
    label: 'Footer Page Id'
    description: 'The page where all the footer content elements are placed'
    type: int #would be great to have a visual choice for a page
    default: ''