ui:
  theme: "light"
  layout:
    radius: "0px"
    rotate: "0"
    pagebg: "white"
    footerbg: "secondary"
    font:
      text: "open-sans"
      heading: "oswald"
  light:
    color:
      primary: "rgb(255, 135, 0)"
      secondary: "rgb(71, 128, 113)"
      light: "rgb(163, 208, 196)"
      primarytext: "var(--color-whitetext)"
      secondarytext: "var(--color-blacktext)"
      lighttext: "var(--color-blacktext)"
  dark:
    color:
      primary: "rgb(205, 156, 19)"
      secondary: "rgb(37, 37, 37)"
      light: "rgb(29, 29, 29)"
      primarytext: "black"
      secondarytext: "var(--color-blacktext)"
      lighttext: "var(--color-blacktext)"

info:
  owner:
    name: "TYPO3 Surfcamp"
    imprint: "https://typo3.org/legal-notice"
    dataPrivacy: "https://typo3.org/privacy-policy"
footer:
  maxCols: '3'
  pageId: 0