ui:
  theme: "light"
  layout:
    radius: "5px"
    rotate: "3deg"
    pagebg: "light"
    footerbg: "light"
    backToTopButton: false
    font:
      text: "lato"
      heading: "playpen-sans"
  light:
    color:
      primary: "#FFC27E"
      secondary: "#A6B067"
      light: "#F9FBEB"
      primarytext: "black"
      secondarytext: "black"
      lighttext: "black"
  dark:
    color:
info:
  owner:
    name: "Poolbar Ltd."
    imprint: "https://www.typo3.com/legal-notice"
    dataPrivacy: "https://www.typo3.com/privacy-policy"
footer:
  maxCols: '2'
  pageId: 0
