services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Surfcamp\Success\:
    resource: '../Classes/*'

  Surfcamp\Success\DataProcessing\PageContentFetchingProcessor:
    tags:
      - { name: 'data.processor', identifier: 'pageContentSuccess' }
