base: 'https://team6.surfcamp.typo3.com/'
baseVariants:
  -
    base: 'https://surfcamp-team6.ddev.site/'
    condition: 'applicationContext == "Development"'
languages:
  -
    title: English
    enabled: true
    locale: en-US
    hreflang: ''
    base: /
    websiteTitle: ''
    navigationTitle: English
    flag: us
    languageId: 0
rootPageId: 5
websiteTitle: ''
dependencies:
  - surfcamp/success-sets-promotion
